server:
  port: 8088

spring:
  application:
    name: fast-generator-data
  profiles:
    active: prodTest

  mvc:
    servlet:
      path: /fast-generator-data

#日志文件路径
logging:
  file:
    path: ./logs
    name: ./logs/all/${spring.application.name}.log
  level: info

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: net.data.generator.entity
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

