server:
  port: 8088

spring:
  application:
    name: fast-generator-data
  profiles:
    active: dev
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.3.8.236:3306/data_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&CatalogMeansCurrent=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      path: /fast-generator-data


#日志文件路径
logging:
  file:
    path: ./logs
    name: ./logs/all/${spring.application.name}.log

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: net.data.generator.entity
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

#测试数据生成
generator:
  data-number: 100000